[project]
name = "preprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WillyJSON", email = "wl_json@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "mne>=1.13.2",
    "numpy>=2.5.3",
    "python-picard>=0.8.2",
    "scipy>=1.18.1",
]

[project.scripts]
preprocessing = "preprocessing:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
